# Generated by Django 4.1 on 2022-08-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.AlterField(
            model_name='client',
            name='cnh_client',
            field=models.CharField(max_length=11, unique=True, verbose_name='CNH'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cpf_client',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='CPF'),
        ),
    ]
