# Generated by Django 4.1 on 2022-08-27 13:50

import client.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_phone_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cnh_client',
            field=models.CharField(max_length=11, unique=True, validators=[client.validators.CNHValidator], verbose_name='CNH'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cpf_client',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, validators=[client.validators.CPFValidator], verbose_name='CPF'),
        ),
    ]
