# Generated by Django 4.1 on 2022-08-27 17:59

from django.db import migrations, models
import validators.docbr


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_phone_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cnh_client',
            field=models.CharField(max_length=11, unique=True, validators=[validators.docbr.CNHValidator()], verbose_name='CNH'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cpf_client',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, validators=[validators.docbr.CPFValidator()], verbose_name='CPF'),
        ),
    ]
