# Generated by Django 4.1 on 2022-08-28 13:55

import django.core.validators
from django.db import migrations, models
from utils import validators


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_client_cnh_client_alter_client_cpf_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='age_client',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(18)], verbose_name='idade'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_client',
            field=models.CharField(max_length=20, validators=[validators.basic_user.PhoneValidator()], verbose_name='telefone'),
        ),
    ]
