# Generated by Django 4.1 on 2022-08-31 22:57

from django.db import migrations, models
from utils import validators


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_client_phone_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cnh_client',
            field=models.CharField(max_length=11, null=True, unique=True, validators=[
                validators.docbr.CNHValidator()], verbose_name='CNH'),
        ),
    ]
