# Generated by Django 4.1 on 2022-08-31 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_client_cnh_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='address_client',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='age_client',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='cpf_client',
            new_name='cpf',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='gender_client',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='phone_client',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='rg_client',
            new_name='rg',
        ),
    ]
