# Generated by Django 4.1.3 on 2023-12-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_rename_address_client_address_person_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='address_person',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='age_person',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='cnh_client',
            new_name='cnh',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='cpf_person',
            new_name='cpf',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='finance_client',
            new_name='finance',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='gender_person',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='phone_person',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='rg_person',
            new_name='rg',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='user_client',
            new_name='user',
        ),
    ]
