# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Insurance(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, title: str=None, coverage: object=None, price: float=None):  # noqa: E501
        """Insurance - a model defined in Swagger

        :param title: The title of this Insurance.  # noqa: E501
        :type title: str
        :param coverage: The coverage of this Insurance.  # noqa: E501
        :type coverage: object
        :param price: The price of this Insurance.  # noqa: E501
        :type price: float
        """
        self.swagger_types = {
            'title': str,
            'coverage': object,
            'price': float
        }

        self.attribute_map = {
            'title': 'title',
            'coverage': 'coverage',
            'price': 'price'
        }
        self._title = title
        self._coverage = coverage
        self._price = price

    @classmethod
    def from_dict(cls, dikt) -> 'Insurance':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Insurance of this Insurance.  # noqa: E501
        :rtype: Insurance
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this Insurance.


        :return: The title of this Insurance.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Insurance.


        :param title: The title of this Insurance.
        :type title: str
        """

        self._title = title

    @property
    def coverage(self) -> object:
        """Gets the coverage of this Insurance.


        :return: The coverage of this Insurance.
        :rtype: object
        """
        return self._coverage

    @coverage.setter
    def coverage(self, coverage: object):
        """Sets the coverage of this Insurance.


        :param coverage: The coverage of this Insurance.
        :type coverage: object
        """

        self._coverage = coverage

    @property
    def price(self) -> float:
        """Gets the price of this Insurance.


        :return: The price of this Insurance.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this Insurance.


        :param price: The price of this Insurance.
        :type price: float
        """

        self._price = price
