# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RentIdBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, driver: List[str]=None):  # noqa: E501
        """RentIdBody - a model defined in Swagger

        :param driver: The driver of this RentIdBody.  # noqa: E501
        :type driver: List[str]
        """
        self.swagger_types = {
            'driver': List[str]
        }

        self.attribute_map = {
            'driver': 'driver'
        }
        self._driver = driver

    @classmethod
    def from_dict(cls, dikt) -> 'RentIdBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The rent_id_body of this RentIdBody.  # noqa: E501
        :rtype: RentIdBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def driver(self) -> List[str]:
        """Gets the driver of this RentIdBody.


        :return: The driver of this RentIdBody.
        :rtype: List[str]
        """
        return self._driver

    @driver.setter
    def driver(self, driver: List[str]):
        """Sets the driver of this RentIdBody.


        :param driver: The driver of this RentIdBody.
        :type driver: List[str]
        """

        self._driver = driver
