# Generated by Django 4.1.3 on 2023-12-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staffmember_user_staffmember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffmember',
            old_name='address_person',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='staffmember',
            old_name='age_person',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='staffmember',
            old_name='branch_staffmember',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='staffmember',
            old_name='cpf_person',
            new_name='cpf',
        ),
        migrations.RenameField(
            model_name='staffmember',
            old_name='gender_person',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='staffmember',
            old_name='phone_person',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='staffmember',
            old_name='rg_person',
            new_name='rg',
        ),
        migrations.RenameField(
            model_name='staffmember',
            old_name='salary_staffmember',
            new_name='salary',
        ),
        migrations.RenameField(
            model_name='staffmember',
            old_name='user_staffmember',
            new_name='user',
        ),
    ]
