# Generated by Django 4.1 on 2022-09-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_rental_appointment_date_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rent_date_rental',
            field=models.DateField(blank=True, null=True, verbose_name='data de alocação'),
        ),
    ]
