# Generated by Django 4.1 on 2022-09-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_alter_rental_appointment_date_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='distance_branch_rental',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='distância entre filiais'),
        ),
    ]
