# Generated by Django 4.1 on 2022-09-15 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_alter_rental_status_rental'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_additionalitems', models.CharField(max_length=50, verbose_name='nome')),
                ('daily_cost_additionalitems', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='custo diário')),
            ],
            options={
                'verbose_name': 'item adicional',
                'verbose_name_plural': 'itens adicionais',
            },
        ),
    ]
