# Generated by Django 4.1.3 on 2022-11-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0012_alter_rental_additional_items_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='additional_items_rental',
            field=models.ManyToManyField(blank=True, null=True, to='rental.additionalitems', verbose_name='itens adicionais'),
        ),
    ]
