# Generated by Django 4.1.3 on 2022-12-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0016_remove_rental_devolution_date_expected_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalitems',
            name='stock_additionalitems',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='quantidade em estoque'),
            preserve_default=False,
        ),
    ]
