# Generated by Django 4.1.3 on 2022-12-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0017_additionalitems_stock_additionalitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalitems',
            name='stock_additionalitems',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='quantidade em estoque'),
        ),
    ]
