# Generated by Django 4.1 on 2022-08-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_vehicle', models.CharField(choices=[('M', 'Moto'), ('C', 'Carro')], default='M', max_length=1, verbose_name='veículo')),
                ('brand_vehicle', models.CharField(max_length=100, verbose_name='marca')),
                ('model_vehicle', models.CharField(max_length=100, verbose_name='modelo')),
                ('year_manufacure_vehicle', models.CharField(max_length=4, verbose_name='ano de fabricação')),
                ('model_year_vehicle', models.CharField(max_length=4, verbose_name='ano do modelo')),
                ('mileage_vehicle', models.FloatField(default=0, verbose_name='quilometragem')),
                ('license_plate_vehicle', models.CharField(max_length=7, unique=True, verbose_name='placa')),
                ('chassi_vehicle', models.CharField(max_length=17, unique=True, verbose_name='chassi')),
                ('fuel_vehicle', models.CharField(choices=[('G', 'Gasolina'), ('E', 'Etanol'), ('D', 'Diesel'), ('H', 'Hibrido')], default='G', max_length=1, verbose_name='combustível')),
                ('fuel_tank_vehicle', models.PositiveSmallIntegerField(verbose_name='capacidade do tanque')),
                ('engine_vehicle', models.CharField(max_length=100, verbose_name='motor')),
                ('color_vehicle', models.CharField(max_length=25, verbose_name='cor')),
                ('other_data_vehicle', models.CharField(blank=True, max_length=500, null=True, verbose_name='mais informações')),
            ],
            options={
                'verbose_name': 'veículo',
            },
        ),
    ]
