# Generated by Django 4.1 on 2022-08-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='available_vehicle',
            field=models.BooleanField(default=True, verbose_name='disponível'),
        ),
    ]
