# Generated by Django 4.1 on 2022-08-24 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_rename_opening_hours_end_branch_opening_hours_end_branch_and_more'),
        ('vehicle', '0003_remove_vehicle_id_alter_vehicle_chassi_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='branch_vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch.branch', verbose_name='filial'),
        ),
    ]
