# Generated by Django 5.0 on 2024-01-08 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_alter_branch_address'),
        ('vehicle', '0018_rename_available_vehicle_vehicle_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branch', verbose_name='filial'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicleclassification', verbose_name='classificação'),
        ),
    ]
