# Generated by Django 5.0.1 on 2024-02-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0019_alter_vehicle_branch_alter_vehicle_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicleclassification',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
