# Generated by Django 4.1 on 2022-08-26 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_vehicle_branch_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='year_manufacure_vehicle',
            new_name='year_manufacture_vehicle',
        ),
    ]
