# Generated by Django 4.1 on 2022-08-31 22:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_alter_vehicle_chassi_vehicle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_classification', models.CharField(max_length=50, verbose_name='classificação')),
                ('daily_cost', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='custo da diária')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='classification_vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.vehicleclassification', verbose_name='classificação'),
        ),
    ]
