# Generated by Django 4.1 on 2022-09-05 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_vehicleclassification_vehicle_classification_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleclassification',
            old_name='daily_cost',
            new_name='daily_cost_classification',
        ),
    ]
