# Generated by Django 4.1 on 2022-09-05 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_rename_daily_cost_vehicleclassification_daily_cost_classification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleclassification',
            options={'verbose_name': 'classificação', 'verbose_name_plural': 'classificações'},
        ),
    ]
