# Generated by Django 4.1 on 2022-09-06 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_alter_vehicleclassification_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='classification_vehicle',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='vehicle.vehicleclassification', verbose_name='classificação'),
            preserve_default=False,
        ),
    ]
