# Generated by Django 4.1 on 2022-09-10 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_rename_opening_hours_end_branch_opening_hours_end_branch_and_more'),
        ('vehicle', '0012_alter_vehicle_classification_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='branch_vehicle',
            field=models.ForeignKey(default=250, on_delete=django.db.models.deletion.DO_NOTHING, to='branch.branch', verbose_name='filial'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='classification_vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vehicle.vehicleclassification', verbose_name='classificação'),
        ),
    ]
