# Generated by Django 4.1 on 2022-09-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0013_alter_vehicle_branch_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image_vehicle',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='imagem'),
        ),
    ]
