# Generated by Django 4.1 on 2022-09-23 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0014_vehicle_image_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='other_data_vehicle',
        ),
    ]
