# Generated by Django 4.1.3 on 2023-12-27 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_rename_cep_address_address_cep_and_more'),
        ('branch', '0003_rename_address_branch_branch_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='address.address', verbose_name='endereço'),
            preserve_default=False,
        ),
    ]
