# Generated by Django 4.1 on 2022-08-22 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'endereço'},
        ),
    ]
