# Generated by Django 5.0.1 on 2024-02-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_rename_address_person_staffmember_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
