# Generated by Django 4.1 on 2022-08-20 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_client', models.CharField(max_length=11, verbose_name='CPF')),
                ('rg_client', models.CharField(max_length=20, verbose_name='RG')),
                ('cnh_client', models.CharField(max_length=11, verbose_name='CNH')),
                ('gender_client', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Não desejo me identificar')], max_length=1, verbose_name='sexo')),
                ('age_client', models.PositiveSmallIntegerField(verbose_name='idade')),
                ('finance_client', models.FloatField(verbose_name='renda')),
                ('address_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address', verbose_name='endereço')),
                ('user_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
        ),
    ]
