# Generated by Django 4.1 on 2022-08-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_client_id_alter_client_cnh_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone_client',
            field=models.CharField(default='19 9 5865 5484', max_length=20, verbose_name='telefone'),
            preserve_default=False,
        ),
    ]
