# Generated by Django 4.1 on 2022-09-01 21:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('client', '0010_rename_address_client_address_person_and_more'),
        ('branch', '0002_rename_opening_hours_end_branch_opening_hours_end_branch_and_more'),
        ('vehicle', '0009_vehicleclassification_vehicle_classification_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_insurance', models.CharField(max_length=100, verbose_name='titulo')),
                ('coverage_insurance', models.JSONField(verbose_name='abrangência')),
            ],
            options={
                'verbose_name': 'seguro',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_rental', models.CharField(choices=[('A', 'Agendado'), ('L', 'Alocado'), ('D', 'Devolvido'), ('E', 'Devolvido com atraso'), ('C', 'Cancelado')], max_length=1, verbose_name='status')),
                ('rent_date_rental', models.DateField(verbose_name='data de alocação')),
                ('devolution_date_rental', models.DateField(verbose_name='data de devolução')),
                ('requested_deadline_rental', models.PositiveSmallIntegerField(verbose_name='prazo requisitado')),
                ('actual_deadline_rental', models.PositiveSmallIntegerField(verbose_name='prazo real')),
                ('fines_rental', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='multas')),
                ('rent_deposit_rental', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='caução')),
                ('daily_cost_rental', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='custo da diária')),
                ('additional_daily_cost_rental', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='custo adicional da diária')),
                ('return_rate_rental', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='taxa de retorno')),
                ('total_cost_rental', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='custo total')),
                ('client_rental', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client.client', verbose_name='cliente')),
                ('outlet_branch_rental', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branch.branch', verbose_name='filial de saída')),
                ('staff_rental', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='staff.staffmember', verbose_name='funcionário')),
                ('vehicle_rental', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vehicle.vehicle', verbose_name='veículo')),
            ],
            options={
                'verbose_name': 'aluguel',
                'verbose_name_plural': 'alugueis',
            },
        ),
    ]
