# Generated by Django 4.1 on 2022-09-02 23:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_rename_address_client_address_person_and_more'),
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='price_insurance',
            field=models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='driver_rental',
            field=models.ManyToManyField(related_name='driver_rental', to='client.client', verbose_name='condutores'),
        ),
        migrations.AddField(
            model_name='rental',
            name='insurance_rental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rental.insurance', verbose_name='seguro'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='client_rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_rental', to='client.client', verbose_name='cliente'),
        ),
    ]
