# Generated by Django 4.1 on 2022-09-03 12:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_rename_opening_hours_end_branch_opening_hours_end_branch_and_more'),
        ('rental', '0002_insurance_price_insurance_rental_driver_rental_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='arrival_branch_rental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='arrival_branch_rental', to='branch.branch', verbose_name='filial de chegada'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='actual_deadline_rental',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='prazo real'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='devolution_date_rental',
            field=models.DateField(blank=True, null=True, verbose_name='data de devolução'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='fines_rental',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='multas'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='outlet_branch_rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='outlet_branch_rental', to='branch.branch', verbose_name='filial de saída'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='return_rate_rental',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='taxa de retorno'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='total_cost_rental',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='custo total'),
        ),
    ]
