# Generated by Django 4.1 on 2022-09-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_rental_arrival_branch_rental_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='appointment_date_rental',
            field=models.DateField(default='2022-08-30', verbose_name='data de agendamento'),
            preserve_default=False,
        ),
    ]
