# Generated by Django 4.1 on 2022-09-05 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_alter_rental_rent_date_rental'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='actual_deadline_rental',
            new_name='actual_days_rental',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='requested_deadline_rental',
            new_name='requested_days_rental',
        ),
    ]
