# Generated by Django 4.1 on 2022-09-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_rename_actual_deadline_rental_rental_actual_days_rental_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='appointment_date_rental',
            field=models.DateField(blank=True, null=True, verbose_name='data de agendamento'),
        ),
    ]
