# Generated by Django 4.1 on 2022-09-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0008_rental_distance_branch_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='status_rental',
            field=models.CharField(choices=[('A', 'Agendado'), ('L', 'Alocado'), ('C', 'Cancelado'), ('D', 'Devolvido')], max_length=1, verbose_name='status'),
        ),
    ]
