# Generated by Django 4.1 on 2022-09-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_additionalitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='additional_items_rental',
            field=models.ManyToManyField(to='rental.additionalitems', verbose_name='itens adicionais'),
        ),
    ]
