# Generated by Django 4.1.3 on 2023-12-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0021_rename_branch_additionalitems_additionalitems_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalitems',
            name='stock',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='quantidade em estoque'),
        ),
    ]
