# Generated by Django 5.0 on 2024-01-08 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_alter_branch_address'),
        ('client', '0011_rename_address_person_client_address_and_more'),
        ('rental', '0022_alter_additionalitems_stock'),
        ('staff', '0003_rename_address_person_staffmember_address_and_more'),
        ('vehicle', '0018_rename_available_vehicle_vehicle_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalitems',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branch', verbose_name='filial'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='arrival_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrival_branch', to='branch.branch', verbose_name='filial de chegada'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='client.client', verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental.insurance', verbose_name='seguro'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='outlet_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_branch', to='branch.branch', verbose_name='filial de saída'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staffmember', verbose_name='funcionário'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='vehicle',
            field=models.ForeignKey(limit_choices_to={'available': True}, on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle', verbose_name='veículo'),
        ),
    ]
