# Generated by Django 5.0.1 on 2024-02-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0023_alter_additionalitems_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalitems',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
