# Generated by Django 4.1 on 2022-08-22 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0002_alter_address_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_hours_start', models.TimeField(verbose_name='início do horário de funcionamento')),
                ('opening_hours_end', models.TimeField(verbose_name='fim do horário de funcionamento')),
                ('address_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address', verbose_name='endereço')),
            ],
            options={
                'verbose_name': 'filial',
                'verbose_name_plural': 'filiais',
            },
        ),
    ]
