# Generated by Django 4.1 on 2022-08-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='opening_hours_end',
            new_name='opening_hours_end_branch',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='opening_hours_start',
            new_name='opening_hours_start_branch',
        ),
        migrations.AddField(
            model_name='branch',
            name='name_branch',
            field=models.CharField(default='Filial das filipinas Imperiais', max_length=100, verbose_name='nome'),
            preserve_default=False,
        ),
    ]
