# Generated by Django 4.1.3 on 2023-12-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_rename_opening_hours_end_branch_opening_hours_end_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='address_branch',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='name_branch',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='opening_hours_end_branch',
            new_name='opening_hours_end',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='opening_hours_start_branch',
            new_name='opening_hours_start',
        ),
    ]
